// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicAntiBlur.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicAntiBlur.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("PendingEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pending_email");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_verification_expiry");

                    b.HasIndex("PendingEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_evt_pending_email_active")
                        .HasFilter("used_at IS NULL AND invalidated_at IS NULL AND purpose = 'bind'");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_user");

                    b.ToTable("email_verification_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_evt_email", "pending_email = lower(btrim(pending_email))");

                            t.HasCheckConstraint("ck_evt_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_evt_invalidated", "invalidated_at IS NULL OR invalidated_at >= created_at");

                            t.HasCheckConstraint("ck_evt_purpose", "purpose IN ('register', 'bind')");

                            t.HasCheckConstraint("ck_evt_terminal", "used_at IS NULL OR invalidated_at IS NULL");

                            t.HasCheckConstraint("ck_evt_used", "used_at IS NULL OR used_at >= created_at");
                        });
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_password_reset_expiry");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_user");

                    b.ToTable("password_reset_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_reset_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_reset_invalidated", "invalidated_at IS NULL OR invalidated_at >= created_at");

                            t.HasCheckConstraint("ck_reset_terminal", "used_at IS NULL OR invalidated_at IS NULL");

                            t.HasCheckConstraint("ck_reset_used", "used_at IS NULL OR used_at >= created_at");
                        });
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("text")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expiry");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("ix_refresh_tokens_parent_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user");

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("ix_refresh_tokens_device");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_revoked", "revoked_at IS NULL OR revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email_lower")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ux_users_login_lower")
                        .HasFilter("login IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_length", "email IS NULL OR (char_length(email) BETWEEN 3 AND 254)");

                            t.HasCheckConstraint("ck_users_email_normalized", "email IS NULL OR email = lower(btrim(email))");

                            t.HasCheckConstraint("ck_users_identifier", "login IS NOT NULL OR email IS NOT NULL");

                            t.HasCheckConstraint("ck_users_login_format", "login IS NULL OR login ~ '^[a-zA-Z0-9_.-]{3,32}$'");

                            t.HasCheckConstraint("ck_users_password_hash", "char_length(password_hash) > 0");

                            t.HasCheckConstraint("ck_users_role", "role IN ('user', 'admin')");

                            t.HasCheckConstraint("ck_users_verified_email", "email_verified_at IS NULL OR email IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PreferredQuality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("auto")
                        .HasColumnName("preferred_quality");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_quality", "preferred_quality IN ('auto', 'aac_128', 'aac_256', 'src')");
                        });
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("MusicAntiBlur.Api.Data.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MusicAntiBlur.Api.Data.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("MusicAntiBlur.Api.Data.Entities.RefreshToken", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_parent_token_id");

                    b.HasOne("MusicAntiBlur.Api.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.UserSettings", b =>
                {
                    b.HasOne("MusicAntiBlur.Api.Data.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("MusicAntiBlur.Api.Data.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicAntiBlur.Api.Data.Entities.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
